### ISSUE TITLE
Tidy up project README & new "contributing" page

### ISSUE THREAD

**Issue by elstoc** [elstoc/dtdocs#135]
Perhaps also move the style guide to a separate document. 

It might be an idea to actually include the style guide as a new "contributing" content page so that people can see both the sample markdown and how it is rendered.

**Comment by paperdigits** [comment]
We should include these pages inside the user guide?

**Comment by matt-maguire** [comment]
I think the intention was more to create a `CONTRIBUTING.md` file alongside the `README.md` file at the root of the repository, in order to simplify the README file.

**Comment by elstoc** [comment]
No the idea was to include it in the user manual itself, probably as the final chapter. I'll knock something up today.
