### ISSUE TITLE
where to document adjustable height modules

### ISSUE THREAD

**Issue by matt-maguire** [elstoc/dtdocs#57]
PR6408 talks about being able to adjust the hiehgt of certain utility modules that contain lists of things by hovering the mouse over the list, then using `Ctrl-scroll` to change the maximum number of items to show in the list at one time.

This applies to modules on both lighttable and darkroom, and currently there is common area in the usermanual where to include such a description of module interaction. So, where to document it?

**Comment by paperdigits** [comment]
There is currently `./darkroom/interacting-with-modules/module-header/` but that doesn't include light table views.

**Comment by matt-maguire** [comment]
Just thought I'd raise it as a ticket so Chris can have a think about how he wants to handle it.

**Comment by elstoc** [comment]
Perhaps an overview at the head of the two module-reference sub-sections?

**Comment by matt-maguire** [comment]
I think it would look a little strange mentioning this one random feature in an "overview" section.

What we have now is:
- user interface section, screen layout talks about panel size (horizintal), maybe it can also talk about module size (vertical)
- module headers are described in the darkroom section, Module hierght could maybe be added after that, but it applies to lighttable modules as well.  
- some lighttable modules also have a header with presets and reset, but no corresponding section. Processing module have extra stuff though like muptiple instances, changing order etc. that are specific to darkroom. 

So, not really sure what we should do here...

**Comment by elstoc** [comment]
Well we could pad the overview out a little too. The only other option in that list that looks reasonable is the first one. Or you mention it in _every_ module! I think an overview for each of the module reference sections would be nice. Brief introduction to what's in the section, perhaps links to other sections that might be of use.
