### ISSUE TITLE
tone-equalizer-cursor.png is not English

### ISSUE THREAD

**Issue by elstoc** [elstoc/dtdocs#6]
The file `module-reference/processing-modules/tone-equalizer/tone-equalizer-cursor.png` looks like it's from a translated (French?) version of darktable and needs to be re-done in an English version, preferably with a more neutral background colour.

**Comment by matt-maguire** [comment]
I guess "IL" is from the French "Indice de Lumination" (my French skills are improving since moving to darktabe lol). I'll generate a better image and put it in a PR.

**Comment by elstoc** [comment]
Thanks @matt-maguire.
