### ISSUE TITLE
retouch module

### ISSUE THREAD

**Issue by matt-maguire** [elstoc/dtdocs#64]
Seems there could be a wrong description of the "merge" slider description for the retouch module:
https://discuss.pixls.us/t/error-in-section-retouch-module-in-darktables-manual-3-0-draft-3-4/20784

Need to take a closer look at this.

**Comment by elstoc** [comment]
dtdocs has the following description:

> This setting allows a common edit to be applied to multiple consecutive scales within a group starting from the coarsest scale (not including the residual image) down to the scale selected. For example, if “merge from” is set to 3 and the maximum scale is 5 then all edits that are added to scale 5 will be applied to scales 3 to 5. Edits added to scale 4 will be applied to scales 3 and 4, and edits added to scale 3 will be applied only to scale 3.

See the attached video where I have retouched scale 5 (the coarsest scale). As I drag the 'merge from' scale slider down, the edit is also applied to the finer scales.

[retouch-2020-10-14_16.39.29.zip](https://github.com/elstoc/dtdocs/files/5379350/retouch-2020-10-14_16.39.29.zip)

I think this accurately describes how it works

**Comment by elstoc** [comment]
Maybe worth mentioning that if there are, say, 6 scales, then "merge from 0" (the default) is the same as "merge from 6" - both mean that the edit will be applied only to the selected scale. If there are only edits on scale 4, say, then "merge from 4, 5 or 6" also all mean the same
