### ISSUE TITLE
odd load and refresh behaviour

### ISSUE THREAD

**Issue by elstoc** [elstoc/dtdocs#69]
When loading a new page, it loads slightly scrolled-down and each time I refresh the page it scrolls down a little more.

On Firefox browser, latest version.

**Comment by matt-maguire** [comment]
I guess it is to bypass the breadcrumbs when first loading the page.

**Comment by elstoc** [comment]
Not sure it's needed though

**Comment by elstoc** [comment]
It's worse if you choose one of the pages at the bottom of the table of contents. For example if I choose the "variables" page, it loads scrolled down by nearly half a page, presumably because the variables section (in the side panel) can't be in the middle of the screen.

**Comment by junkyardsparkle** [comment]
I don't understand why it refreshes the TOC frame at all... it is, indeed, extremely annoying. I wasn't paying attention to that, and moved the pointer down one line after reading one section, clicked, and found myself in a completely different part of the manual. :-/

**Comment by paperdigits** [comment]
I am going to re-code the navigation so that sections are collapsed by default. I'm open to other ideas on how the navigation should look, given that it is quite long.

**Comment by paperdigits** [comment]
This is fixed in 3091490eba980fafb38d119978a1387c2eaae667, let me know if this meets your expectation.

**Comment by elstoc** [comment]
Yep. Fixed for me. Thanks @paperdigits.
