### ISSUE TITLE
website needs to support multiple manuals

### ISSUE THREAD

**Issue by matt-maguire** [elstoc/dtdocs#88]
As identified in #86, need to push usermanual down a level to allow room for the LUA API manual beside it. Need to be able to generate separate PDFs for usermanual and LUA API guide.

**Comment by elstoc** [comment]
A question for @paperdigits I suppose - should we just create a pair of top level directories for the darktable and lua API manuals or is there a better way to do it?

**Comment by paperdigits** [comment]
Are we going to keep the LUA and dt API manuals up-to-date? Do we want separate hugo repos for those or do we want them all in the same repo? 

If we want them all in the same repo, it is just shifting everything we currently have into a "darktable user manual" folder, then creating new folders for the LUA and dt API stuff.

**Comment by johnny-bit** [comment]
2 ways that i see:
1. 3 repos: dtdocs (user manual), dtluadocs(lua), dtapidocs (api)
2. 3 dirs under dtdocs: usermanual, lua, api

i wonder what will in practice be the best bet.

**Comment by elstoc** [comment]
Yes I don't know. I kind of prefer the idea of a separate repo for each manual though I'd keep it to 2 only. The non-API docs are pretty small and imo fine to keep in the main manual as a sort of 'taster'. Given that most of the non-content stuff is done via submodules I don't know that there's much difference between the options. In the end it's more a question of what will be preferred when this gets absorbed into darktable-org

**Comment by paperdigits** [comment]
If we want separate repos, they can all use the same theme and what not.

**Comment by wpferguson** [comment]
> Are we going to keep the LUA and dt API manuals up-to-date? Do we want separate hugo repos for those or do we want them all in the same repo?

I'll keep the Lua API manual up to date.  I maintain the xml one now and there aren't many changes so maintaining them both is fine.

> Somebody express an opinion please :)

Currently the darktable tree has src/external/... for external projects such as rawspeed, libxcf, lua, etc.  

Why not doc/external/... for the documentation, using submodules?  @TurboGit, thoughts?

 I don't have a problem with separate repositories for each manual.  The only concern I would have is keeping the boilerplate (themes, etc.) in sync to maintain the same look and feel.  I think the user manual will have lots of changes each year.  The Lua API manual only has a couple, so maintaining it isn't that much effort and I'm willing to take that on.  

I'm also looking at the 3.4 release and trying to anticipate what's going to happen with the lua scripts.  This will be the first release where average users (aka, non-programmers) will have the ability to access the lua scripts by just pointing and clicking.  The only documentation for the scripts is in the header comments which I display as a tool tip in script_manager.  I"m thinking of using this same framework for a lua scripts manual and a lua scripts API manual so there is some documentation to point the users at when the release drops.

**Comment by TurboGit** [comment]
> Why not doc/external/... for the documentation, using submodules? @TurboGit, thoughts?

Yes, that's my plan when we switch to the new user's manual.

**Comment by elstoc** [comment]
> The only concern I would have is keeping the boilerplate (themes, etc.) in sync to maintain the same look and feel.

I think most of that stuff is handled with submodules anyway so probably not a major issue.

**Comment by wpferguson** [comment]
Then I vote for separate repositories.  That spreads the workload, responsibility and allows more flexibility, i.e. one manual isn't holding up the other from releasing.

**Comment by elstoc** [comment]
Let's call that decision made then. I've created a separate repo and asked @paperdigits to set it up.

**Comment by elstoc** [comment]
New repo has been initialised by @paperdigits and @wpferguson has been set as a maintainer, so I guess this issue is closed.

**Comment by wpferguson** [comment]
Thanks @elstoc and @paperdigits
