### ISSUE TITLE
Make all menu headers clickable

### ISSUE THREAD

**Issue by elstoc** [elstoc/dtdocs#92]
In the left-hand menu pane, some section headers are clickable and some are not (generally depending on whether there is written content in that section). However, this makes for a sometimes odd looking menu (mixture of links and headers) and means that you have to click on the + to get to a viewable page (which is quite a small target) and isn't consistent with the breadcrumbs (and some section links) which do allow you to access those header pages.

Please make the entire menu navigable by clicking on the section names as well as the + signs. When clicking on a section that doesn't contain any content, it should load the same page as if you clicked on the breadcrumb link to that page.

**Comment by paperdigits** [comment]
Fixed in 602b7a45662bd9f00db0058fc11a34fc72578f84
