### ISSUE TITLE
more modules has been removed from code

### ISSUE THREAD

**Issue by matt-maguire** [elstoc/dtdocs#93]
dtdocs still has a section on "more modules" (`module reference->utility modules->darkroom->more modules`), but in fact this was removed from the code in PR#5683 iop layouts. I didn't notice this, because I don't always clear out my install directory, and I still had an old .so file for "more modules" on my system that was being picked up and displayed in the gui. With a clean installation directory however, you can see this module no longer exists.

**Comment by matt-maguire** [comment]
The "more modules" reference page is also referred to by:
```
./content/overview/workflow/edit-overview.md
./content/darkroom/darkroom-view-layout.md
```
Those pages will need an updated text to align with the new module groups approach,

**Comment by elstoc** [comment]
ok I'll push an update
