### ISSUE TITLE
Tone EQ

### ISSUE THREAD

**Issue by kofa73** [elstoc/dtdocs#99]
module-reference/processing-modules/tone-equalizer/

> This controls how much of the surrounding image to take into account when calculating the mask’s blur at a particular point. By default it takes 25% of the surrounding into account.

'25% of the surrounding(s)' doesn't really mean anything. Checking the code, the blurring radius is defined in terms of image dimensions (`d->blending` is the value entered on the UI as 'smoothing diameter'), even though the exact calculation is not that important from a user's point of view:
```
  const int max_size = (piece->iwidth > piece->iheight) ? piece->iwidth : piece->iheight;
  const float diameter = d->blending * max_size * roi_in->scale;
  const int radius = (int)((diameter - 1.0f) / ( 2.0f));
```
So, it could perhaps be worded as 'This controls how much of the surrounding image to take into account when calculating the mask’s blur at a particular point, in relation to the image dimensions. The default value is 25% of the longest side.'
Maybe including the values Aurélien considered typical would make sense: 'Typical blurring radii are around 1-5% [for EIGF], while the original GF is better between 10-25%' (https://discuss.pixls.us/t/a-tone-equalizer-in-darktable/10678/10).

**Comment by kofa73** [comment]
or 'defined as a ratio/fraction of the longer side' (certainly not longest, as there are just 2...)

**Comment by matt-maguire** [comment]
I see what you mean by "taking 25% of the surroundings" is a bit confisuing, and is even not really accurate. Thanks for the suggestion.

The manual hasn't been updated yet for the new EIGF masking algorithm, it still refers to the original GF only.
